const changeColorVariablesConstant = [
    "REACT_APP_DISABLE_BG_DARK_COLOR",
    "REACT_APP_DISABLE_TEXT_DARK_COLOR",
    "REACT_APP_TOAST_SUCCESS_DARK_BG",
    "REACT_APP_TOAST_SUCCESS_DARK_TEXT",
    "REACT_APP_TOAST_INFO_DARK_BG",
    "REACT_APP_TOAST_INFO_DARK_TEXT",
    "REACT_APP_TOAST_FAIL_DARK_BG",
    "REACT_APP_TOAST_FAIL_DARK_TEXT",
]

export default changeColorVariablesConstant